version: "2.1"

services:
  app:
    build: app
    labels:
      io.balena.features.balena-api: 1
    volumes:
      - keys:/keys
      - cache:/cache
      - backups:/backups
      - config:/config
    privileged: true
    tmpfs:
      - /tmp
      - /var/tmp
      - /run
      - /var/run

volumes:
  keys:
  cache:
  backups:
  config:
