name: balena

on:
  # push:
  #   branches:
  #     - "main"
  #   tags:
  #     - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - id: balena_ci
        uses: balena-io/balena-ci@v0.1.0
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ secrets.BALENA_FLEET_SLUG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: false
          environment: balena-cloud.com

      - id: balena_api
        if: ${{ steps.balena_ci.outputs.release_id }}
        shell: bash
        run: |
          raw_version="$(curl -fsSL -X GET \
            "https://api.balena-cloud.com/v6/release(${{ steps.balena_ci.outputs.release_id }})?\$select=version" \
            -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.BALENA_API_KEY }}" | jq -r '.d[].version.raw')"
          echo "::set-output name=raw_version::$raw_version"

      - id: tagger
        if: ${{ steps.balena_api.outputs.raw_version }}
        uses: tvdias/github-tagger@v0.0.2
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "v${{ steps.balena_api.outputs.raw_version }}"
